name: ci

on:
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:

jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [ubuntu-latest]
    steps:
      - name: echo
        run: echos this is ci run