name: slack

on:
  workflow_run:
    workflows: [ci, deploy, delete]
    branches: [main]
    types:
      - completed

jobs:
  slack-failure-notification:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: [ubuntu-latest]
    steps:
      - name: echo
        run: echo ${{ github.event.workflow.name}}

      - name: Slack Notification
        uses: gdcorp-action-public-forks/action-slack-notify@a8f00dc3dbe3d3e876546e2f3334139c19a6bac9
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: "Github Workflow"
          SLACK_MESSAGE: "build fails on workflow ${{ github.event.workflow.name}}"
          SLACK_COLOR: "#FF0000"
          SLACK_USERNAME: 'github-actions'
          SLACK_ICON: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'